In [1]:
import numpy as np
import pandas as pd

1. **Creating** a **DataFrame**

In [6]:
data = {
    'name': ['John', 'Anna', 'Peter', 'Linda'],
    'age': [28, 24, 35, 32],
    'city': ['New York', 'Paris', 'Berlin', 'London'],
    'salary': [50000, 60000, 55000, 65000]
}
df = pd.DataFrame(data)

In [7]:
df

    name  age      city  salary
0   John   28  New York   50000
1   Anna   24     Paris   60000
2  Peter   35    Berlin   55000
3  Linda   32    London   65000

using list

In [10]:
data_list = [
    ['John', 'Anna', 'Peter', 'Linda'],
    [28, 24, 35, 32],
    ['New York', 'Paris', 'Berlin', 'London'],
    [50000, 60000, 55000, 65000]
]
df2 = pd.DataFrame(data_list)

In [11]:
df2

          0      1       2       3
0      John   Anna   Peter   Linda
1        28     24      35      32
2  New York  Paris  Berlin  London
3     50000  60000   55000   65000