In [1]:
import numpy as np
import pandas as pd

1. **Creating** a **DataFrame**

In [20]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 24, 35, 32],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [50000, 60000, 55000, 65000]
}
df = pd.DataFrame(data)

In [21]:
df

    Name  Age      City  Salary
0   John   28  New York   50000
1   Anna   24     Paris   60000
2  Peter   35    Berlin   55000
3  Linda   32    London   65000

using list

In [22]:
data_list = [
    ['John', 'Anna', 'Peter', 'Linda'],
    [28, 24, 35, 32],
    ['New York', 'Paris', 'Berlin', 'London'],
    [50000, 60000, 55000, 65000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]
df2_columns = pd.DataFrame(data_list, columns= columns)

In [23]:
df2

          0      1       2       3
0      John   Anna   Peter   Linda
1        28     24      35      32
2  New York  Paris  Berlin  London
3     50000  60000   55000   65000

In [24]:
df2_columns

       Name    Age    City  Salary
0      John   Anna   Peter   Linda
1        28     24      35      32
2  New York  Paris  Berlin  London
3     50000  60000   55000   65000

2. **Selection** and **Indexing** of a **Column**

In [25]:
df

    Name  Age      City  Salary
0   John   28  New York   50000
1   Anna   24     Paris   60000
2  Peter   35    Berlin   55000
3  Linda   32    London   65000

Targeting a single coumn

In [26]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

Targeting multiple columns

In [27]:
df[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

3. **Creating a new column**

In [29]:
df['Designation'] = ['Doctor', 'Engineer', 'Doctor', 'Engineer']

In [30]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   50000      Doctor
1   Anna   24     Paris   60000    Engineer
2  Peter   35    Berlin   55000      Doctor
3  Linda   32    London   65000    Engineer

4. **Remove a Column**

In [31]:
df.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   50000
1   Anna   24     Paris   60000
2  Peter   35    Berlin   55000
3  Linda   32    London   65000