In [3]:
import numpy as np
import pandas as pd

**Merging two dataframes**

In [4]:
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'employee_name':['John','Jane','Jack','Jill','Jerry'],
    'department' :['HR','IT','Finance','IT','HR']
})

salaries = pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[50000,60000,70000,80000,90000],
    'bonus':[5000,6000,7000,8000,9000]
})

In [5]:
employees

   employee_id employee_name department
0            1          John         HR
1            2          Jane         IT
2            3          Jack    Finance
3            4          Jill         IT
4            5         Jerry         HR

In [6]:
salaries

   employee_id  salary  bonus
0            1   50000   5000
1            2   60000   6000
2            3   70000   7000
3            6   80000   8000
4            7   90000   9000

In [ ]:
pd.merge(employees,salaries) # automatically does on the basis of common column

   employee_id employee_name department  salary  bonus
0            1          John         HR   50000   5000
1            2          Jane         IT   60000   6000
2            3          Jack    Finance   70000   7000

on keyword

In [ ]:
pd.merge(employees,salaries,on='employee_id') # on -> provided the common column

   employee_id employee_name department  salary  bonus
0            1          John         HR   50000   5000
1            2          Jane         IT   60000   6000
2            3          Jack    Finance   70000   7000

how keyword

In [10]:
pd.merge(employees,salaries,on='employee_id',how='inner') # how is inner by default

   employee_id employee_name department  salary  bonus
0            1          John         HR   50000   5000
1            2          Jane         IT   60000   6000
2            3          Jack    Finance   70000   7000

In [12]:
pd.merge(employees,salaries,on='employee_id',how='outer') # outer -> all the records from both the dataframes, 
                                                          # if there is no match then it will fill with NaN

   employee_id employee_name department   salary   bonus
0            1          John         HR  50000.0  5000.0
1            2          Jane         IT  60000.0  6000.0
2            3          Jack    Finance  70000.0  7000.0
3            4          Jill         IT      NaN     NaN
4            5         Jerry         HR      NaN     NaN
5            6           NaN        NaN  80000.0  8000.0
6            7           NaN        NaN  90000.0  9000.0

In [13]:
pd.merge(employees,salaries,on='employee_id',how='left') # left -> all the records from the left dataframe, 
                                                          # if there is no match then it will fill with NaN

   employee_id employee_name department   salary   bonus
0            1          John         HR  50000.0  5000.0
1            2          Jane         IT  60000.0  6000.0
2            3          Jack    Finance  70000.0  7000.0
3            4          Jill         IT      NaN     NaN
4            5         Jerry         HR      NaN     NaN

In [14]:
pd.merge(employees,salaries,on='employee_id',how='right') # right -> all the records from the right dataframe,
                                                          # if there is no match then it will fill with NaN

   employee_id employee_name department  salary  bonus
0            1          John         HR   50000   5000
1            2          Jane         IT   60000   6000
2            3          Jack    Finance   70000   7000
3            6           NaN        NaN   80000   8000
4            7           NaN        NaN   90000   9000

**Concatination of two dataframes**

In [15]:
df1 = pd.DataFrame({
    'A' : ['A0','A1','A2'],
    'B' : ['B0','B1','B2'],
    'C' : ['C0','C1','C2'],
})

df2 = pd.DataFrame({
    'A' : ['A3','A4','A5'],
    'B' : ['B3','B4','B5'],
    'C' : ['C3','C4','C5'],
})

In [16]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [17]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2]) # on the basis of columns, axis = 0 by default

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2], axis=1) # on the basis of rows, axis = 1

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining two dataframes**

In [21]:
df1 = pd.DataFrame({
    'name' : ['John','Jane','Jack'],
}, index=[1,2,3])

df2 = pd.DataFrame({
    'score' : [90,80,70],
}, index=[2,3,4])

In [22]:
df1

   name
1  John
2  Jane
3  Jack

In [23]:
df2

   score
2     90
3     80
4     70

In [24]:
df1.join(df2)

   name  score
1  John    NaN
2  Jane   90.0
3  Jack   80.0