# GroupBy and Aggregation in Pandas

This notebook demonstrates grouping and summarizing sales data using Pandas:

- Create a DataFrame with `Category`, `Store`, `Sales`, `Quantity`, and `Date`
- Group by a single column and sum sales:
  - `df.groupby('Category')['Sales'].sum()`
  - `df.groupby('Store')['Sales'].sum()`
- Group by multiple columns:
  - `df.groupby(['Store', 'Category'])['Sales'].sum()`
- Perform aggregation on a column:
  - `df['Sales'].mean()`
  - `df['Sales'].agg(['mean','sum','median','min','max'])`

These operations help summarize data and compare performance across groups.

In [2]:
import numpy as np
import pandas as pd

**Group By**

In [4]:
data = {
    'Category' : ['A','B','A','B','A','B','A','B'],
    'Store' : ['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales' : [100,200,150,250,120,180,130,220],
    'Quantity' : [10,20,15,25,12,18,13,22],
    'Date' : pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [5]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        20 2023-01-02
2        A    S2    150        15 2023-01-03
3        B    S2    250        25 2023-01-04
4        A    S1    120        12 2023-01-05
5        B    S2    180        18 2023-01-06
6        A    S2    130        13 2023-01-07
7        B    S1    220        22 2023-01-08

Group by category and calculate the sum of sales

In [6]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    500
B    850
Name: Sales, dtype: int64

Group by store and calculate the sum of sales

In [7]:
st = df.groupby('Store')['Sales'].sum()
st

Store
S1    640
S2    710
Name: Sales, dtype: int64

Group by multiple columns

In [10]:
mul = df.groupby(['Store','Category'])['Sales'].sum()
mul

Store  Category
S1     A           220
       B           420
S2     A           280
       B           430
Name: Sales, dtype: int64

**Aggregation**

In [12]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        20 2023-01-02
2        A    S2    150        15 2023-01-03
3        B    S2    250        25 2023-01-04
4        A    S1    120        12 2023-01-05
5        B    S2    180        18 2023-01-06
6        A    S2    130        13 2023-01-07
7        B    S1    220        22 2023-01-08

mean

In [11]:
df['Sales'].mean() # you can do more of this with median, min, max, count, std, sum etc

np.float64(168.75)

aggregation function

In [15]:
df['Sales'].agg(['mean','sum','median','min','max'])

mean       168.75
sum       1350.00
median     165.00
min        100.00
max        250.00
Name: Sales, dtype: float64